// On-device ECDSA-P256 verify test fixture (jrwagz/marquee-scroller#100).
//
// jrwagz asked for proof that the new ECDSA-P256 verify path behaves exactly
// as expected on real ESP8266 hardware (the prior round swapped HMAC-SHA256
// → ECDSA-P256 in 09b76b2 after he correctly pointed out that a build-time
// HMAC key is trivially extractable from the public firmware bin).  This
// fixture compiles into the firmware only when -DWAGFAM_HW_VERIFY_TEST=1 is
// set, runs immediately in setup() before any networking, hits the SAME
// verifyConfigUpdateSignature() path the production poll uses, and prints
// one [ECDSA-TEST] line per case to Serial so the result is greppable.
//
// Coverage:
//   1. positive — valid sig + key + payload                        → expect TRUE
//   2. wrong-signature — sig was made for a DIFFERENT payload      → expect FALSE
//   3. wrong-public-key — sig is fine, key is from a 2nd keypair   → expect FALSE
//   4. truncated-payload — sign full, verify against payload[:-1]  → expect FALSE
//   5. mutated-payload — sign canonical, verify against 1-byte-flip → expect FALSE
//   6. mutated-signature — flip 1 byte in the 64-byte raw r||s     → expect FALSE
//   7. wrong-prefix-pubkey — replace 0x04 with 0x02 (compressed)   → expect FALSE
//   8. empty-pubkey — pass ""                                       → expect FALSE
//
// Cases 7 and 8 hit the early-reject paths in verifyConfigUpdateSignature
// (the 130-char hex length check and the 0x04-prefix check); cases 1-6
// exercise the BearSSL ECDSA path itself (br_ecdsa_i15_vrfy_raw with
// br_ec_p256_m15) and should round-trip bit-identically with what
// jrwagz/wagfam-server's signing path emits.
//
// Fixtures live in the marker block below and are regenerated by
// scripts/sign_test_payloads.py.

#include "HwVerifyTest.h"

#ifdef WAGFAM_HW_VERIFY_TEST

#include <Arduino.h>

#include "ConfigUpdateVerify.h"

// === HARNESS-GENERATED FIXTURES — do not edit by hand ===
// Regenerate via: python3 scripts/sign_test_payloads.py --write
// Source private keys live in scripts/test_keys/ (gitignored).
// Each constant pairs with a TestCase row in kCases[].  No
// PROGMEM marker — on ESP8266 Arduino, static const char[] already
// lives in flash without it, and skipping FPSTR() keeps the test
// path identical to how production code calls verifyConfigUpdate-
// Signature (which takes String& and const char*).

static const char kPubKeyMainHex[]      = "04494ae598a1add74d0034ed910175fd4ba4619943c9ebe3e1d556bafd8a2cae1ef2c3a9651a90b963308b7e79059f2c5477b1c3f9a4439b6f05d3ccca160c59d5";
static const char kPubKeyAltHex[]       = "0482f8d9b2c7214cd708bcf803d11257511d5389acd25b149681a156907235c8acd3e14a5c9de5d0f58999e66dd666bcfbf1474d66fb0e5f6aa61c6683ce2c79de";
static const char kPubKeyWrongPrefix[]  = "02494ae598a1add74d0034ed910175fd4ba4619943c9ebe3e1d556bafd8a2cae1ef2c3a9651a90b963308b7e79059f2c5477b1c3f9a4439b6f05d3ccca160c59d5";

static const char kPayloadCanonical[]   = "{\"trollMessage\":\"hardware verify test\",\"configUpdateVersion\":42}";
static const char kPayloadMutated[]     = "{\"trollMessage\":\"Hardware verify test\",\"configUpdateVersion\":42}";
static const char kPayloadTruncated[]   = "{\"trollMessage\":\"hardware verify test\",\"configUpdateVersion\":42";
// kSigForOtherB64 was made over: '{"trollMessage":"different message","configUpdateVersion":1}'
//   (recorded as a comment, not a runtime constant — the verify
//    test only uses the SIGNATURE of this payload, not the bytes.)

static const char kSigCanonicalB64[]    = "M82Uod4Oe2MjqcnGtz/9K+t4ODf5eb2SzlYgaZlMO67GyH/BQFoglEI41HatI1r2Y1eL0tDkvq5iyIYYJKEvoQ==";
static const char kSigForOtherB64[]     = "DIXpREuO5oo8OePLt2kXkn9YdBesyERLxCtzYghYGmKQit+v/P81IZktZ/95U8I9IdNKLxjKzFzhfkCycI3EfA==";
static const char kSigMutatedB64[]      = "Ms2Uod4Oe2MjqcnGtz/9K+t4ODf5eb2SzlYgaZlMO67GyH/BQFoglEI41HatI1r2Y1eL0tDkvq5iyIYYJKEvoQ==";

// === END HARNESS-GENERATED FIXTURES ===

namespace {

struct TestCase {
  const char *name;
  const char *payload;
  const char *signatureBase64;
  const char *publicKeyHex;
  bool expected;
};

void runOne(const TestCase &tc, uint8_t &passes) {
  // Construct the same argument shapes verifyConfigUpdateSignature sees in
  // production (marquee.ino's poll handler around line 1133).  String for
  // payload + sig (because both come from JSON deserialization there),
  // const char* for the pubkey (because production passes
  // WAGFAM_CONFIG_PUBLIC_KEY directly).
  String payload(tc.payload);
  String signatureBase64(tc.signatureBase64);
  bool got = verifyConfigUpdateSignature(payload, signatureBase64, tc.publicKeyHex);
  bool ok = (got == tc.expected);
  Serial.print(F("[ECDSA-TEST] "));
  Serial.print(tc.name);
  Serial.print(F(": "));
  Serial.print(ok ? F("PASS") : F("FAIL"));
  Serial.print(F(" (expected="));
  Serial.print(tc.expected ? F("true") : F("false"));
  Serial.print(F(", got="));
  Serial.print(got ? F("true") : F("false"));
  Serial.println(F(")"));
  if (ok) passes++;
  // Each verify is ~30ms; yield between cases so the soft watchdog stays
  // happy even if BearSSL ends up doing more work than expected.
  yield();
}

}  // namespace

void runHwVerifyTest() {
  // Give the host's serial terminal a moment to attach after reset.  Without
  // this the first few lines can be eaten when the user opens minicom/screen
  // a heartbeat after the device boots.
  delay(500);
  Serial.println();
  Serial.println(F("[ECDSA-TEST] === ECDSA-P256 verify hardware test (PR #100) ==="));
  Serial.println(F("[ECDSA-TEST] Fixtures from scripts/sign_test_payloads.py"));
  Serial.println(F("[ECDSA-TEST] Each case calls verifyConfigUpdateSignature() — same path as the production poll."));

  const TestCase kCases[] = {
      // 1. The positive case proves the BearSSL P-256 verify accepts a
      //    signature that was produced by the matching private key over the
      //    exact bytes we pass in.  If THIS one fails, the rest are noise.
      {"01_positive",                kPayloadCanonical, kSigCanonicalB64,  kPubKeyMainHex,     true},
      // 2. Same payload + same key, but the signature was produced over a
      //    *different* payload.  Sig is well-formed (still 64 bytes raw),
      //    but the digest mismatch should make ECDSA reject.
      {"02_wrong_signature",         kPayloadCanonical, kSigForOtherB64,   kPubKeyMainHex,     false},
      // 3. Sig + payload are consistent, but we verify with a public key
      //    from a different keypair.  Tests that the verify is actually
      //    using the supplied key, not some cached state.
      {"03_wrong_public_key",        kPayloadCanonical, kSigCanonicalB64,  kPubKeyAltHex,      false},
      // 4. Truncated payload — drops the trailing '}'.  Same key+sig, but
      //    SHA-256 of the shorter byte string mismatches.
      {"04_truncated_payload",       kPayloadTruncated, kSigCanonicalB64,  kPubKeyMainHex,     false},
      // 5. Mutated payload — one ASCII byte flipped ('h' → 'H').  Catches a
      //    class of bug where the implementation hashes a constant or
      //    capitalisation-folded version instead of the bytes-as-received.
      {"05_mutated_payload",         kPayloadMutated,   kSigCanonicalB64,  kPubKeyMainHex,     false},
      // 6. Mutated signature — one byte flipped in the raw 64-byte r||s
      //    *before* base64.  Still decodes to 64 bytes, just isn't a valid
      //    sig anymore.  Tests that we're not just length-checking.
      {"06_mutated_signature",       kPayloadCanonical, kSigMutatedB64,    kPubKeyMainHex,     false},
      // 7. Pubkey hex starts with 0x02 instead of 0x04.  Hits the early-
      //    reject branch in verifyConfigUpdateSignature — should fail
      //    BEFORE BearSSL is even called.  We mandate uncompressed form
      //    because we control both ends of the pipe.
      {"07_wrong_prefix_pubkey",     kPayloadCanonical, kSigCanonicalB64,  kPubKeyWrongPrefix, false},
      // 8. Empty pubkey — the firmware default when WAGFAM_CONFIG_PUBLIC_KEY
      //    isn't passed at build time.  Hits the very first check in
      //    verifyConfigUpdateSignature; this is the "fail closed" path.
      {"08_empty_pubkey",            kPayloadCanonical, kSigCanonicalB64,  "",                 false},
  };

  uint8_t passes = 0;
  const uint8_t total = sizeof(kCases) / sizeof(kCases[0]);
  unsigned long startMs = millis();
  for (uint8_t i = 0; i < total; i++) {
    runOne(kCases[i], passes);
  }
  unsigned long elapsedMs = millis() - startMs;

  Serial.print(F("[ECDSA-TEST] DONE: "));
  Serial.print(passes);
  Serial.print(F("/"));
  Serial.print(total);
  Serial.print(F(" passed in "));
  Serial.print(elapsedMs);
  Serial.println(F(" ms"));
  Serial.println(F("[ECDSA-TEST] === halting; reset the device to re-run ==="));

  // Halt — feed the watchdog so the device stays alive and the user has
  // time to scroll up in the serial monitor.  Re-print the summary every
  // 30s so it's easy to find no matter when serial is attached.
  unsigned long lastEchoMs = millis();
  while (true) {
    yield();
    delay(100);
    if (millis() - lastEchoMs > 30000UL) {
      Serial.print(F("[ECDSA-TEST] (still halted) DONE: "));
      Serial.print(passes);
      Serial.print(F("/"));
      Serial.print(total);
      Serial.println(F(" passed"));
      lastEchoMs = millis();
    }
  }
}

#endif  // WAGFAM_HW_VERIFY_TEST
